### ISSUE TITLE
Config conflict gives NoneType exception

### ISSUE THREAD

**Issue by inki2** [ALBA-Synchrotron/pyIcePAP#36]
Use case:
We have a configuration conflict situation (DB - driver board) for some driver in a system.

Symptom:
When starting up IcePAPcms and selecting the system in the selection tree, IcePAPcms will call function getDriverConfiguration() for all drivers. This function calls pyIcePAP property IcePAPAxis.config() which throws an exception "'NoneType' object has no attribute '__getitem__'".

@rhomspuron This is a problem to me since I deliberately have a conflict situation for some drivers in my test system in Lund. In every branch I need to comment out some code to be able to run IcePAPcms. I sent you an e-mail 2018-10-24, 15:20 with title "pyIcePAP axis config exeption".

**Comment by rhomspuron** [comment]
Hi @inki2, 

Thanks for reporting this issue, we should analyze if the protection should be on the client (IcepapCMS) or on the library, but the question is: what should return the library in case of conflicts on the axis.

**Comment by inki2** [comment]
@rhomspuron Now I don't quite remember all the details since this was a few months ago (and I took for granted that the intended functionality was well known) but I think that there is an internal error in pyIcePap that is the cause of the thrown exception. Let me know if you want me to take a look and refresh my memory.

**Comment by rhomspuron** [comment]
@inki2 I check the code of the IcePAPAxis.config() method and how IcepapCMS uses it, and after we can evaluate if we include the protection on pyIcePAP or IcepapCMS
