### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by PhilLAL** [ALBA-Synchrotron/pyIcePAP#44]
Hello there,
doing some tests for icepapcms, I noticed that pyIcePAP needs at least numpy installed (perhaps other dependencies exists but are already installed).

Is there a list of these dependencies somewhere? 
Thank you.

**Comment by rhomspuron** [comment]
Hi @PhilLAL, 

Thanks for report it.  There is not documentation of the dependencies, we will include them on the setup.py

**Comment by PhilLAL** [comment]
Thank you Roberto,
you can also include a `requirements` file. This could help when installing through pip since dependencies can then be installed automatically.
`pip freeze > requirements.txt` can be a good base and you can clean it before commiting it. Some explanatation are given in https://pip.pypa.io/en/stable/user_guide/#requirements-files 

Regards.

**Comment by rhomspuron** [comment]
Hi PhiLAL, 

We update all requirements on the setup.py. We will prepare the installation on pip for the python 3 version. 

Regards
