### ISSUE TITLE
EthIcePAPController interface

### ISSUE THREAD

**Issue by tiagocoutinho** [ALBA-Synchrotron/pyIcePAP#45]
The current EthIcePAPController object acts in an intelligent way which introspect the hardware to find version and present racks and axes. 
* asking for the version is problematic is the hardware is under heavy stress (ex: another connection that asked to move a motor and is querying the motor state frequently to know when it stops)
* the amount of discovery slows down the object creation and consequently the applications that use them

The current behaviour is still very useful for creating a very verbose object which takes care of many things underneath. But it would be nice to have an alternative mode that solves the above problems.

We propose that EthIcePAPController API work in two modes:
* intelligent (default in 2.8.x): in the constructor we introspect the hardware to see what
  axes are present and we initialize the internal state with these axes. This is the current behaviour in 2.8.x.
 * advanced (would be default in 3.x): the constructor is lazy and it is up to the user of the object to request specific axes and manage their destruction

Here is an excerpt of how the advanced mode could look like:

```python
ice = EthIcePAPController('icepap12', auto_axes=False)
5 in ice                # False
ice.keys()              # = []
# return True
a5 = ice[5]             # a5 instance IcePAPAxis
ice.keys()              # = [5]
ice.values()            # = [IcePAPAxis(5)]
p = ice[5].pos          # p is int
p = ice[55].pos        # raise IcePAPError('unknown axis') if axis does not exist
p = ice['th'].pos        # raise IcePAPError('unknown axis') if axis does not exist
p = ice[12700].pos      # raise IcePAPError('unknown axis')
ice.add_alias('th', 5)
th = ice['th']          # th instance IcePAPAxis
th is a5                # return True
th in ice               # raise False
5 in ice                # return True
ice.get_pos(5)          # int with steps
ice.get_pos('th')       # int with steps

ice.find_axes() # list all existing axis numbers
ice.find_axes(filter=lambda axis: axis.alive) # list all alive axis numbers
ice.update_axes() # fills dict with existing axis by asking hardware which are the existing axes
ice[5] is th          # this invariant should remain true

del ice[5]        # == ice.pop(5) removes axis 5 from known axes
```

**Comment by rhomspuron** [comment]
Great!. I addition I would like to remove the heritage from a dictionary. In this case the methods keys() and values() should not use them, instead we should use axes() and drivers(). The method items() can be useful. 

Note: The methods keys() and values() will be deprecated up to version 3.x 

In that case the code should be: 

 ```python
ice = EthIcePAPController('icepap12', auto_axes=False)
5 in ice                # False
ice.axes()              # = []
# return True
a5 = ice[5]             # a5 instance IcePAPAxis
ice.axes()              # = [5]
ice.drivers()            # = [IcePAPAxis(5)]
p = ice[5].pos          # p is int
p = ice[55].pos        # raise IcePAPError('unknown axis') if axis does not exist
p = ice['th'].pos        # raise IcePAPError('unknown axis') if axis does not exist
p = ice[12700].pos      # raise IcePAPError('unknown axis')
ice.add_alias('th', 5)
th = ice['th']          # th instance IcePAPAxis
th is a5                # return True
th in ice               # raise False
5 in ice                # return True
ice.get_pos(5)          # int with steps
ice.get_pos('th')       # int with steps

ice.find_axes() # list all existing axis numbers
ice.find_axes(filter=lambda axis: axis.alive) # list all alive axis numbers
ice.update_axes() # fills dict with existing axis by asking hardware which are the existing axes
ice[5] is th          # this invariant should remain true

for axis, driver in ice.items():
     print(axis, dirver.pos)           # this prints the axis number and the position of the axis

for axis in ice:
    print(axis)                         # this prints the axis number
del ice[5]        # == ice.pop(5) removes axis 5 from known axes
```
