### ISSUE TITLE
Problems with icepap communication

### ISSUE THREAD

**Issue by tiagocoutinho** [ALBA-Synchrotron/pyIcePAP#60]
Hi,
I found several issues with the icepap communication. 
I will put them all here.

### handle asynchronous exception (ex: Keyboard Interrupt)

during a call for the icepap it is not possible to do ctrl+c and have a recover.
example:
```
m3 = ice[3]
try:
    m3.move(target)
    while m3.ge_tstate().is_moving():
        time.sleep(0.1)
except KeyboardInterrupt:
    m3.stop()
```
If the ctrl+c happens during the call to `get_state()` the icepap tries to start reconnection thread but when the `m3.stop()` line is executed, the connection is not ready so the call to `stop()` fails.

### masked errors
Some `OSError` and even a `BaseException` is being masked to `RuntimeError`.
This makes it harder to handle errors since I cannot easily understand on my application what real error happened.
IMHO the library should just handle the error and re-raise or simply don't do anything

### separate application protocol and connection
Not an error, just a suggestion:
The low level `SocketCon` class is handling both TCP connection and half of the icepap protocol. The other half seems to be managed by the `IcePAPCommunication`.
It would be create if the concerns are separated. This way you could eventually use another connection class (like serial line for example... not that anyone wants that :-)

**Comment by rhomspuron** [comment]
Hi @tiagocoutinho ,

Thanks for report them. You're right all the exception are manage like RuntimeError, it was a heritage from the original version. I will review the code to remove this management. 

We can improve the re-connection and the classes SocketCon and IcePAPCommunication, on the beginning the idea was support both connections TCP and Serial, I would like to do not close the possibility to connect by serial line, but it is real that we do not use it :-)

**Comment by tiagocoutinho** [comment]
Hi @rhomspuron ,
Before you invest your time, I wanted to make a proposal which I have almost ready. I am quite happy with it.
