### ISSUE TITLE
Problems with python3.9, array.tostring() is replaced by .tobytes()

### ISSUE THREAD

**Issue by HEnquist** [ALBA-Synchrotron/pyIcePAP#70]
`tostring()` has been deprecated since python 3.2, and was removed completely in 3.9.
The replacement is `tobytes()`, which works the same. 
Problem is here:
https://github.com/ALBA-Synchrotron/pyIcePAP/blob/master/icepap/communication.py#L136

**Comment by HEnquist** [comment]
Yes I intended to! Will do asap.

**Comment by rhomspuron** [comment]
https://bugs.python.org/issue38916
